version: '3.8'
services:
  crawler:
    container_name: social_health_crawler
    image: social_crawler
    networks:
      - social-network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: unless-stopped

  postgres:
    container_name: social_health_db
    image: timescale/timescaledb:latest-pg14
    networks:
      - social-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
      - ./config/postgres/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    container_name: social_health_redis
    image: redis:latest
    networks:
      - social-network
    volumes:
      - ./redis_data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis-custom.conf
    restart: unless-stopped
    command: ["redis-server", "--include /usr/local/etc/redis/redis-custom.conf"]

networks:
  social-network:
    driver: bridge

volumes:
    redis_data:
